[package]
name = "fedora-updater"
version = "0.1.0"
edition = "2021"
authors = ["khs-kks"]
repository = "https://github.com/khs-kks/fedora-updater"
description = "A command-line utility to update Fedora systems through Flatpak and DNF5"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
colored = "=3.0.0"